### ISSUE TITLE
Screenshot : no download in firefox

### ISSUE THREAD

**Issue by mbredif** [itownsResearch/demo-geoid#6]
In firefox 48 (Ubuntu), the screenshot does not trigger any download.
the console correctly logs  `screenshot : X/Y` messages and `screenshot : done`.

**Comment by LAREG-OJ** [comment]
Idem in Firefox 49.0.1, MacOS X.
Solved by adding "document.body.appendChild(element);" in the callback of function "canvas.toBlob".
